-- Database Schema for Jaham Secondary School
-- Generated by EVI for EvNr

CREATE DATABASE IF NOT EXISTS jaham_school;
USE jaham_school;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL DEFAULT '123',
  `role` enum('admin','teacher','student') NOT NULL DEFAULT 'student',
  `grade_level` varchar(10) DEFAULT NULL,
  `section` varchar(10) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`name`, `email`, `password`, `role`, `grade_level`, `section`) VALUES
('الأستاذة صابرين', 'sabreen@academy.com', '123', 'teacher', NULL, NULL),
('EvNr', 'evnr@academy.com', '123', 'student', '10', NULL),
('أروى فهد العازمي', 'student2@academy.com', '123', 'student', '10', NULL),
('الاء ياسر العازمي', 'student3@academy.com', '123', 'student', '10', NULL),
('المى بدر العتيبي', 'student4@academy.com', '123', 'student', '10', NULL),
('أمل سيف العتيبي', 'student5@academy.com', '123', 'student', '10', NULL),
('حلا حامد العتيبي', 'student6@academy.com', '123', 'student', '10', NULL),
('حنين محمد العازمي', 'student7@academy.com', '123', 'student', '10', NULL),
('حور فواز العازمي', 'student8@academy.com', '123', 'student', '10', NULL),
('رانيا اسامه سید', 'student9@academy.com', '123', 'student', '10', NULL),
('ربی حمد العازمي', 'student10@academy.com', '123', 'student', '10', NULL),
('رند عقاب العازمي', 'student11@academy.com', '123', 'student', '10', NULL),
('رهف محمد العازمي', 'student12@academy.com', '123', 'student', '10', NULL),
('ريتاج وليد العتيبي', 'student13@academy.com', '123', 'student', '10', NULL),
('ريماس ضيف الله العازمي', 'student14@academy.com', '123', 'student', '10', NULL),
('ریمان خالد العتيبي', 'student15@academy.com', '123', 'student', '10', NULL),
('شجن محمد العتيبي', 'student16@academy.com', '123', 'student', '10', NULL),
('شذى حامد العتيبي', 'student17@academy.com', '123', 'student', '10', NULL),
('عذاري راجح العازمي', 'student18@academy.com', '123', 'student', '10', NULL),
('غاليه غزاي العتيبي', 'student19@academy.com', '123', 'student', '10', NULL),
('غلاء مفرح العتيبي', 'student20@academy.com', '123', 'student', '10', NULL),
('غنى عمر العازمي', 'student21@academy.com', '123', 'student', '10', NULL),
('فجر سلطان العازمي', 'student22@academy.com', '123', 'student', '10', NULL),
('لارا معتق العتيبي', 'student23@academy.com', '123', 'student', '10', NULL),
('المار سلطان العازمي', 'student24@academy.com', '123', 'student', '10', NULL),
('المار فهد العتيبي', 'student25@academy.com', '123', 'student', '10', NULL),
('ليان عيد الغبيوي', 'student26@academy.com', '123', 'student', '10', NULL),
('مريم عايض الروقي', 'student27@academy.com', '123', 'student', '10', NULL),
('منى موسى العتيبي', 'student28@academy.com', '123', 'student', '10', NULL),
('نورا عوض العتيبي', 'student29@academy.com', '123', 'student', '10', NULL),
('هدى حكيم العتيبي', 'student30@academy.com', '123', 'student', '10', NULL),
('هوازن مرزوق الروقي', 'student31@academy.com', '123', 'student', '10', NULL),
('بتول ضيف الله العازمي', 'student32@academy.com', '123', 'student', '11', 'A'),
('بدريه مقعد العازمي', 'student33@academy.com', '123', 'student', '11', 'A'),
('جود سعدي العازمي', 'student34@academy.com', '123', 'student', '11', 'A'),
('رهف رجاء العازمي', 'student35@academy.com', '123', 'student', '11', 'A'),
('ريما سعدي العازمي', 'student36@academy.com', '123', 'student', '11', 'A'),
('ريماس عبد الرحمن العتيبي', 'student37@academy.com', '123', 'student', '11', 'A'),
('سجى سعد العازمي', 'student38@academy.com', '123', 'student', '11', 'A'),
('سمر مطر العازمي', 'student39@academy.com', '123', 'student', '11', 'A'),
('سميرة مطر العازمي', 'student40@academy.com', '123', 'student', '11', 'A'),
('عبير عياد العازمي', 'student41@academy.com', '123', 'student', '11', 'A'),
('المياء خالد العازمي', 'student42@academy.com', '123', 'student', '11', 'A'),
('ميسون مفلح العتيبي', 'student43@academy.com', '123', 'student', '11', 'A'),
('نجلاء عايض العتيبي', 'student44@academy.com', '123', 'student', '11', 'A'),
('نوف سلمي العازمي', 'student45@academy.com', '123', 'student', '11', 'A'),
('وعد سلمان العازمي', 'student46@academy.com', '123', 'student', '11', 'A'),
('اريج فرج العازمي', 'student47@academy.com', '123', 'student', '11', 'B'),
('دانه عبد المحسن العازمي', 'student48@academy.com', '123', 'student', '11', 'B'),
('دانه مسحل العازمي', 'student49@academy.com', '123', 'student', '11', 'B'),
('رانيه سهيل العازمي', 'student50@academy.com', '123', 'student', '11', 'B'),
('رهام مخلد العازمي', 'student51@academy.com', '123', 'student', '11', 'B'),
('ريناد خالد العتيبي', 'student52@academy.com', '123', 'student', '11', 'B'),
('شجون مغير العتيبي', 'student53@academy.com', '123', 'student', '11', 'B'),
('شذى فهد الروقي', 'student54@academy.com', '123', 'student', '11', 'B'),
('عهود شنيف العازمي', 'student55@academy.com', '123', 'student', '11', 'B'),
('غلا مغير العتيبي', 'student56@academy.com', '123', 'student', '11', 'B'),
('منى سطام العازمي', 'student57@academy.com', '123', 'student', '11', 'B'),
('مها سعود العازمي', 'student58@academy.com', '123', 'student', '11', 'B'),
('نوره مرزوق الروقي', 'student59@academy.com', '123', 'student', '11', 'B'),
('هبه سعود العازمي', 'student60@academy.com', '123', 'student', '11', 'B'),
('اروى فواز تويلي', 'student61@academy.com', '123', 'student', '12', 'A'),
('العنود رشيد العازمي', 'student62@academy.com', '123', 'student', '12', 'A'),
('حور ماجد العازمي', 'student63@academy.com', '123', 'student', '12', 'A'),
('خلود شنيف العازمي', 'student64@academy.com', '123', 'student', '12', 'A'),
('رغد عقاب العازمي', 'student65@academy.com', '123', 'student', '12', 'A'),
('ريماس سعدي العازمي', 'student66@academy.com', '123', 'student', '12', 'A'),
('ريماس عبد الله الروقي', 'student67@academy.com', '123', 'student', '12', 'A'),
('ريناد عزيز العازمي', 'student68@academy.com', '123', 'student', '12', 'A'),
('ريوف راشد العازمي', 'student69@academy.com', '123', 'student', '12', 'A'),
('ريوف فرج العازمي', 'student70@academy.com', '123', 'student', '12', 'A'),
('ساره فواز العازمي', 'student71@academy.com', '123', 'student', '12', 'A'),
('سلطانه مسلط العازمي', 'student72@academy.com', '123', 'student', '12', 'A'),
('شجعا فرج العازمي', 'student73@academy.com', '123', 'student', '12', 'A'),
('شیهانه بدر تويلي', 'student74@academy.com', '123', 'student', '12', 'A'),
('عبير صويلح العازمي', 'student75@academy.com', '123', 'student', '12', 'A'),
('فجر خالد العازمي', 'student76@academy.com', '123', 'student', '12', 'A'),
('مريم نور العازمي', 'student77@academy.com', '123', 'student', '12', 'A'),
('مي موسى المرشدي', 'student78@academy.com', '123', 'student', '12', 'A'),
('نجلاء عبد الله العازمي', 'student79@academy.com', '123', 'student', '12', 'A'),
('نجود مرزوق العازمي', 'student80@academy.com', '123', 'student', '12', 'A'),
('وجدان سعد الغبيوي', 'student81@academy.com', '123', 'student', '12', 'A'),
('وضحى سعود العازمي', 'student82@academy.com', '123', 'student', '12', 'A'),
('اروى فواز العازمي', 'student83@academy.com', '123', 'student', '12', 'B'),
('اسيل حمد العازمي', 'student84@academy.com', '123', 'student', '12', 'B'),
('الجوهره صنيتان الدلبحي', 'student85@academy.com', '123', 'student', '12', 'B'),
('الدانة عبد الهادي العازمي', 'student86@academy.com', '123', 'student', '12', 'B'),
('رهف عواض الروقي', 'student87@academy.com', '123', 'student', '12', 'B'),
('روند وليد العازمي', 'student88@academy.com', '123', 'student', '12', 'B'),
('ريتاج غالب العازمي', 'student89@academy.com', '123', 'student', '12', 'B'),
('ريم حامد الدلبحي', 'student90@academy.com', '123', 'student', '12', 'B'),
('ريما فلاح العازمي', 'student91@academy.com', '123', 'student', '12', 'B'),
('ريماس تركي العازمي', 'student92@academy.com', '123', 'student', '12', 'B'),
('ساره مقعد العازمي', 'student93@academy.com', '123', 'student', '12', 'B'),
('سحر عوض العازمي', 'student94@academy.com', '123', 'student', '12', 'B'),
('سهام حمدي الروقي', 'student95@academy.com', '123', 'student', '12', 'B'),
('شهد حامد الدلبحي', 'student96@academy.com', '123', 'student', '12', 'B'),
('شهد رجاء العازمي', 'student97@academy.com', '123', 'student', '12', 'B'),
('غلاء صالح العازمي', 'student98@academy.com', '123', 'student', '12', 'B'),
('نجود راشد العازمي', 'student99@academy.com', '123', 'student', '12', 'B'),
('ندى محمد العازمي', 'student100@academy.com', '123', 'student', '12', 'B'),
('وجدان سلمان العازمي', 'student101@academy.com', '123', 'student', '12', 'B'),
('ياسمين خالد العازمي', 'student102@academy.com', '123', 'student', '12', 'B');

-- --------------------------------------------------------

--
-- Table structure for table `chat_messages`
--

CREATE TABLE IF NOT EXISTS `chat_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sender_name` varchar(255) NOT NULL,
  `role` varchar(50) NOT NULL DEFAULT 'student',
  `message` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `chat_messages`
--

INSERT INTO `chat_messages` (`sender_name`, `role`, `message`) VALUES
('الأستاذة صابرين', 'teacher', 'مرحباً بكم في منصة التواصل. يمكنكم طرح الأسئلة هنا.');
